from selenium import webdriver
driver = webdriver.Chrome(executable_path=r'/Users/tess/Desktop/seleniumChrome/chromedriver')
driver.get("file:///Users/tess/Desktop/seleniumChrome/html_code_02.html")
login_form = driver.find_element_by_id('loginForm')
print("Here is my login form variable printed below")
print(login_form)
username = driver.find_element_by_name('username')
print("Here is the username of the form: ")
print(username)

elt_by_absolute_path = driver.find_element_by_xpath("/html/body/form[1]")
print("Form by absolute path: ")
print(elt_by_absolute_path)
elt_by_relative_path = driver.find_element_by_xpath("//form[1]")
print("Form by relative path: ")
print(elt_by_relative_path)
elt_by_id_path = driver.find_element_by_xpath("//form[@id='loginForm']")
print("Form by more specific relative path via ID" )
print(elt_by_id_path)

content = driver.find_element_by_class_name("content")
print("Pick element by Class Name: ")
print(content)
driver.close()
